#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

# Node LTS
image: cypress/included:8.4.1

pipelines:
  branches:
    '{master,develop}':
      - step:
          name: Build and test
          caches:
            - node
            - npm
            - cypress
          script:
            - export CYPRESS_imageSnaphots="true"
            - yarn install
            - yarn bootstrap
            - yarn build
            - yarn lint
            - yarn test
          artifacts:
            - packages/**/cypress/snapshots/**/__diff_output__/*.diff.png
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress
